# Generated by Django 6.0.4 on 2026-04-25 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('APPROVE_SUBMISSION', 'Approve Submission'), ('POST_ADMIN_LEDGER', 'Post Admin Ledger'), ('CREATE_INVESTMENT', 'Create Investment'), ('RELEASE_INVESTMENT_FUNDS', 'Release Investment Funds'), ('CLOSE_INVESTMENT', 'Close Investment'), ('DISTRIBUTE_PL', 'Distribute Pl'), ('REVERSE_DISTRIBUTION', 'Reverse Distribution'), ('VIEW_ALL_REPORTS', 'View All Reports'), ('MANAGE_USERS', 'Manage Users')], max_length=60, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'permissions_permission',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('user_permission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants_made', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='permissions.permission')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants_revoked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permissions_userpermission',
                'indexes': [models.Index(fields=['user', 'is_active'], name='permissions_user_id_e85efd_idx')],
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
