# Generated by Django 6.0.4 on 2026-04-25 09:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('investment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('investment_type', models.CharField(choices=[('FIXED_DEPOSIT', 'Fixed Deposit'), ('EQUITY', 'Equity / Shares'), ('REAL_ESTATE', 'Real Estate'), ('LENDING', 'Lending / Loan'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('invested_to', models.CharField(max_length=300)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('fund_released_at', models.DateTimeField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('return_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pnl_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('closure_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('DISTRIBUTED', 'Distributed'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments_created', to=settings.AUTH_USER_MODEL)),
                ('fund_released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investments_released', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investments_investment',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['status', 'created_date'], name='investments_status_d7df84_idx')],
            },
        ),
    ]
