# Generated by Django 6.0.4 on 2026-04-25 09:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalSubmissionRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('INSTALLMENT', 'Installment'), ('SUBMISSION', 'Capital Submission')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('txn_date', models.DateField()),
                ('payment_channel', models.CharField(choices=[('HAND_CASH', 'Hand Cash'), ('BKASH', 'bKash'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('resulting_ledger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_submission', to='ledger.membercapitalledgerentry')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions_capitalsubmissionrequest',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mime_type', models.CharField(max_length=100)),
                ('byte_size', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions_fileattachment',
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissions.fileattachment')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='submissions.capitalsubmissionrequest')),
            ],
            options={
                'db_table': 'submissions_submissionattachment',
            },
        ),
        migrations.AddIndex(
            model_name='capitalsubmissionrequest',
            index=models.Index(fields=['user', 'status'], name='submissions_user_id_e65954_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalsubmissionrequest',
            index=models.Index(fields=['status', 'requested_at'], name='submissions_status_a6b01c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionattachment',
            unique_together={('submission', 'file')},
        ),
    ]
