# Generated by Django 6.0.4 on 2026-04-25 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentSnapshotHeader',
            fields=[
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_capital', models.DecimalField(decimal_places=2, max_digits=18)),
                ('member_count', models.PositiveIntegerField()),
                ('snapshot_time', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='investments.investment')),
            ],
            options={
                'db_table': 'snapshots_investmentsnapshotheader',
            },
        ),
        migrations.CreateModel(
            name='InvestmentSnapshotLine',
            fields=[
                ('snapshot_line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capital_at_snapshot', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ratio', models.DecimalField(decimal_places=10, max_digits=18)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='snapshots.investmentsnapshotheader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snapshots_investmentsnapshotline',
                'ordering': ['-capital_at_snapshot'],
                'unique_together': {('snapshot', 'user')},
            },
        ),
    ]
