# Generated by Django 6.0.4 on 2026-04-25 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        ('ledger', '0001_initial'),
        ('snapshots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentDistribution',
            fields=[
                ('distribution_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pnl_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rounded_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remainder_applied', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=10)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='investments.investment')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions_posted', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions_reversed', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snapshots.investmentsnapshotheader')),
            ],
            options={
                'db_table': 'distributions_investmentdistribution',
            },
        ),
        migrations.CreateModel(
            name='InvestmentDistributionLine',
            fields=[
                ('distribution_line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ratio_used', models.DecimalField(decimal_places=10, max_digits=18)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='distributions.investmentdistribution')),
                ('ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.membercapitalledgerentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'distributions_investmentdistributionline',
            },
        ),
        migrations.AddConstraint(
            model_name='investmentdistribution',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'POSTED')), fields=('investment',), name='unique_posted_distribution_per_investment'),
        ),
        migrations.AlterUniqueTogether(
            name='investmentdistributionline',
            unique_together={('distribution', 'user')},
        ),
    ]
