# Generated by Django 6.0.4 on 2026-04-25 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCapitalLedgerEntry',
            fields=[
                ('ledger_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('SUBMISSION', 'Capital Submission'), ('WITHDRAW', 'Withdrawal'), ('ADJUSTMENT', 'Admin Adjustment'), ('DISTRIBUTION', 'P/L Distribution'), ('DISTRIBUTION_REVERSAL', 'Distribution Reversal')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='BDT', max_length=5)),
                ('txn_date', models.DateField()),
                ('reference_type', models.CharField(choices=[('INVESTMENT', 'Investment'), ('MANUAL', 'Manual'), ('SYSTEM', 'System'), ('SUBMISSION_REQUEST', 'Submission Request')], max_length=30)),
                ('reference_id', models.CharField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledger_membercapitalledgerentry',
                'ordering': ['txn_date', 'created_at'],
                'indexes': [models.Index(fields=['user', 'txn_date'], name='ledger_memb_user_id_56008b_idx'), models.Index(fields=['reference_type', 'reference_id'], name='ledger_memb_referen_d11376_idx'), models.Index(fields=['entry_type'], name='ledger_memb_entry_t_89839d_idx')],
            },
        ),
    ]
