# Generated by Django 6.0.4 on 2026-04-25 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('RELEASE_FUNDS', 'Release Funds'), ('CLOSE', 'Close'), ('DISTRIBUTE', 'Distribute'), ('REVERSE', 'Reverse'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('GRANT_PERM', 'Grant Perm'), ('REVOKE_PERM', 'Revoke Perm'), ('DEACTIVATE_USER', 'Deactivate User')], db_index=True, max_length=30)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_auditlog',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['entity_name', 'entity_id'], name='audit_audit_entity__09005e_idx'), models.Index(fields=['actor', 'occurred_at'], name='audit_audit_actor_i_50d0aa_idx')],
            },
        ),
    ]
